output_dir: '../../data/tcells_hv/HV6_Tcells_Dapi_gH2AX__lamin_31_5_21_2X_16bit/features/'
module: src.pipelines.feature_extraction
class: MultiChannelFeatureExtractionPipeline3D
run_params:
  input_dir: '../../data/tcells_hv/HV6_Tcells_Dapi_gH2AX__lamin_31_5_21_2X_16bit/segmented/concomp_2d/nuclear_crops_3d'
  channels: ['dapi', 'gh2ax', 'lamin']


pipeline:
  - method: run_default_pipeline
    params:
      segmentation_params_dict: { 'method': 'morph_snakes', 'min_size': 400, 'iterations': 300, 'lambda1': 1, 'lambda2': 2 }
      characterize_channels: ['gh2ax','lamin']

