output_dir: '../../data/sample1_02_25_21/tcells_dapi_lamina_hp1_500nm/features/'
module: src.pipelines.feature_extraction
class: DnaFeatureExtractionPipeline3D
run_params:
  input_dir: '../../data/sample1_02_25_21/tcells_dapi_lamina_hp1_500nm/segmented/segmentation_watershed_2d/nuclear_crops'
  channels: ['dapi', 'hp1a', 'lamin']


pipeline:
  - method: run_default_pipeline

