output_dir: '../../data/hmf3a_data_23_04_2021/hmf3a_tnfa5ng_dapi_hp1_actin/dna_features/'
module: src.pipelines.feature_extraction
class: MultiChannelFeatureExtractionPipeline3D
run_params:
  input_dir: '../../data/hmf3a_data_23_04_2021/hmf3a_tnfa5ng_dapi_hp1_actin/segmented/concomp_2d/nuclear_crops_3d'
  channels: ['dapi', 'hp1', 'actin']


pipeline:
  - method: run_default_pipeline
    params:
      segmentation_params_dict: {'method':'threshold_otsu', 'min_size': 400,  'median_smoothing': False, 'gamma': 1.0}
      characterize_channels: ['hp1']
      compute_rdp: False

