output_dir: '../../data/condition_media/hmf3a_09_04_2021/condition_media/dapi_hp1_h3k9me3/segmented/'
module: src.pipelines.nuclei_segmentation
class: NucleiSegmentationPipeline
run_params:
  input_dir: '../../data/condition_media/hmf3a_09_04_2021/condition_media/dapi_hp1_h3k9me3/raw/'

pipeline:
  - method: run_default_pipeline
    params:
      min_area: 10000
      max_area: 40000
      gamma: 0.4
      morphological_closing: False
      filter_type: "median"

