output_dir: '../../data/tcells_hv/HV6_Tcells_Dapi_gH2AX__lamin_31_5_21_2X_16bit/segmented/'
module: src.pipelines.nuclei_segmentation
class: NucleiSegmentationPipeline
run_params:
  input_dir: '../../data/tcells_hv/HV6_Tcells_Dapi_gH2AX__lamin_31_5_21_2X_16bit/raw/'

pipeline:
  - method: run_default_pipeline
    params:
      min_area: 500
      max_area: 6000
      gamma: 1.0
      morphological_closing: False
      filter_type: "median"