output_dir: '../../data/condition_media/hmf3a_09_04_2021/condition_media/dapi_hp1_h3k9me3/features/'
module: src.pipelines.feature_extraction
class: MultiChannelFeatureExtractionPipeline3D
run_params:
  input_dir: '../../data/condition_media/hmf3a_09_04_2021/condition_media/dapi_hp1_h3k9me3/segmented/concomp_2d/nuclear_crops_3d'
  channels: ['dapi', 'hp1', 'h3k9me3']


pipeline:
  - method: run_default_pipeline
    params:
      segmentation_params_dict: {'method':'threshold_otsu', 'min_size': 400,  'median_smoothing': True, 'gamma': 1.1}
      characterize_channels: ['hp1']

